version: '3'

services:
  vim-container:
    container_name: my-vim-container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/workspace
    tty: true
    command: /bin/bash -c "/workspace/scripts/make_symlink.sh && zsh"