version: "3.9"

services:
  vim-container:
    container_name: vim-container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/workspace
    tty: true
    command: zsh
