version: "3"

services:
  vim-container:
    container_name: vim-container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/workspace
    tty: true
    command: /bin/bash -c "/workspace/scripts/link.sh && zsh"
