require('base')
require('keymap')
require('autocmds')

require('plugins')
require('nvim-tree-d')
require('gruvbox-d')
require('mason-d')
require('cmp-d')
require('telescope-d')
require('dressing-d')
require('lualine-d')
require('tabline-d')
require('mini-indentscope-d')
require('nvim-treesitter-d')
require('notice-d')
require('gitsigns-d')